language: python
sudo: required
python:
  - "3.7"

install: "pip install -r requirements.txt"

before_install:
  - sudo apt-get install -y gdal-bin

env:
  - DJANGO_SETTINGS_MODULE=planning_finder.settings.local EMAIL_HOST_USER=EMAIL_HOST_USER EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD SPATIALITE_LIBRARY_PATH=some_path

script: ./manage.py test